version: "3"
services:
  kgtk-browser-iswc:
    image: docker-reg.ads.isi.edu:443/kgtk-browser:iswc
    command: sh -c "flask run --host 0.0.0.0 --port 5007"
    container_name: kgtk-browser-iswc
    restart: always
    ports:
      - "5007:5007"
    volumes:
      - /data:/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"
networks:
  default:
    external:
      name: overlay

